name: LimitHeight
main: LimitHeight\LimitHeight
version: 1.4
api: [3.0.0-ALPHA7, 3.0.0-ALPHA8, 3.0.0-ALPHA9, 3.0.0-ALPHA10, 3.0.0-ALPHA11, 3.0.0-ALPHA12]
load: STARTUP
author: EvolSoft
description: A simple plugin to limit the build height on your server.
website: https://www.evolsoft.tk

permissions:
 limitheight:
  default: op
  description: LimitHeight permissions tree.
  children:
    limitheight.bypass:
      default: op
      description: Let players bypass the height limit.